

const fyersService = require("./fyers.service");
const websocketService = require("./websocket.service");

// const UNDERLYINGS = [
//     "NSE:ADANIENSOL-EQ",
//     "NSE:ADANIGREEN-EQ",
//     "NSE:ADANIPORTS-EQ",
//     "NSE:AMBUJACEM-EQ",
//     "NSE:ANGELONE-EQ",
//     "NSE:APLAOLLO-EQ",
//     "NSE:ASIANPAINT-EQ",
//     "NSE:ATGL-EQ",
//     "NSE:AUBANK-EQ",
//     "NSE:AUROPHARMA-EQ",
//     "NSE:BAJAJ-AUTO-EQ",
//     "NSE:BAJAJFINSV-EQ",
//     "NSE:BAJFINANCE-EQ",
//     "NSE:BHARATFORG-EQ",
//     "NSE:BHARTIARTL-EQ",
//     "NSE:BSE-EQ",
//     "NSE:CAMS-EQ",
//     "NSE:CDSL-EQ",
//     "NSE:CGPOWER-EQ",
//     "NSE:CHAMBLEFERT-EQ",
//     "NSE:CHOLAFIN-EQ",
//     "NSE:CIPLA-EQ",
//     "NSE:CYIENT-EQ",
//     "NSE:DEEPAKNTR-EQ",
//     "NSE:DIVISLAB-EQ",
//     "NSE:DIXON-EQ",
//     "NSE:DLF-EQ",
//     "NSE:DMART-EQ",
//     "NSE:DRREDDY-EQ",
//     "NSE:EICHERMOT-EQ",
//     "NSE:ESCORTS-EQ",
//     "NSE:GODREJCP-EQ",
//     "NSE:GODREJPROP-EQ",
//     "NSE:HAL-EQ",
//     "NSE:HAVELLS-EQ",
//     "NSE:HCLTECH-EQ",
//     "NSE:HDFCAMC-EQ",
//     "NSE:HDFCLIFE-EQ",
//     "NSE:HINDALCO-EQ",
//     "NSE:HINDUNILVR-EQ",
//     "NSE:ICICIGI-EQ",
//     "NSE:INDHOTEL-EQ",
//     "NSE:INDIANB-EQ",
//     "NSE:INDIGO-EQ",
//     "NSE:INDUSINDBK-EQ",
//     "NSE:INFY-EQ",
//     "NSE:IRCTC-EQ",
//     "NSE:JINDALSTEL-EQ",
//     "NSE:JSL-EQ",
//     "NSE:JSWENERGY-EQ",
//     "NSE:JSWSTEEL-EQ",
//     "NSE:JUBLFOOD-EQ",
//     "NSE:KALYANKJIL-EQ",
//     "NSE:KEI-EQ",
//     "NSE:LAURUSLABS-EQ",
//     "NSE:LICHSGFIN-EQ",
//     "NSE:LODHA-EQ",
//     "NSE:LUPIN-EQ",
//     "NSE:MARUTI-EQ",
//     "NSE:MAXHEALTH-EQ",
//     "NSE:MCX-EQ",
//     "NSE:MFSL-EQ",
//     "NSE:MGL-EQ",
//     "NSE:MPHASIS-EQ",
//     "NSE:MUTHOOTFIN-EQ",
//     "NSE:NAUKRI-EQ",
//     "NSE:OBEROIRLTY-EQ",
//     "NSE:PAYTM-EQ",
//     "NSE:PERSISTENT-EQ",
//     "NSE:PHOEXIXLTD-EQ",
//     "NSE:PIDILITIND-EQ",
//     "NSE:PIINDI-EQ",
//     "NSE:POLICYBZR-EQ",
//     "NSE:POLYCAB-EQ",
//     "NSE:PRESTIGE-EQ",
//     "NSE:RAMCOCEM-EQ",
//     "NSE:SHREECEM-EQ",
//     "NSE:SHRIRAMFIN-EQ",
//     "NSE:SIEMENS-EQ",
// ];


const UNDERLYINGS = [
    "NSE:ABB-EQ",
    "NSE:ACC-EQ",
    "NSE:APLAPOLLO-EQ",
    "NSE:AUBANK-EQ",
    "NSE:AARTIIND-EQ",
    "NSE:ADANIENSOL-EQ",
    "NSE:ADANIENT-EQ",
    "NSE:ADANIGREEN-EQ",
    "NSE:ADANIPORTS-EQ",
    "NSE:ATGL-EQ",
    "NSE:ALKEM-EQ",
    "NSE:AMBUJACEM-EQ",
    "NSE:ANGELONE-EQ",
    "NSE:APOLLOHOSP-EQ",
    "NSE:ASIANPAINT-EQ",
    "NSE:ASTRAL-EQ",
    "NSE:AUROPHARMA-EQ",
    "NSE:DMART-EQ",
    "NSE:AXISBANK-EQ",
    "NSE:BSOFT-EQ",
    "NSE:BSE-EQ",
    "NSE:BAJAJ-AUTO-EQ",
    "NSE:BAJFINANCE-EQ",
    "NSE:BAJAJFINSV-EQ",
    "NSE:BALKRISIND-EQ",
    "NSE:BANDHANBNK-EQ",
    "NSE:BANKBARODA-EQ",
    "NSE:BDL-EQ",
    "NSE:BEL-EQ",
    "NSE:BHARATFORG-EQ",
    "NSE:BHARTIARTL-EQ",
    "NSE:BLUESTARCO-EQ",
    "NSE:BOSCHLTD-EQ",
    "NSE:BRITANNIA-EQ",
    "NSE:CGPOWER-EQ",
    "NSE:CDSL-EQ",
    "NSE:CHAMBLFERT-EQ",
    "NSE:CHOLAFIN-EQ",
    "NSE:CIPLA-EQ",
    "NSE:COFORGE-EQ",
    "NSE:COLPAL-EQ",
    "NSE:CAMS-EQ",
    "NSE:CONCOR-EQ",
    "NSE:CUMMINSIND-EQ",
    "NSE:CYIENT-EQ",
    "NSE:DLF-EQ",
    "NSE:DABUR-EQ",
    "NSE:DALBHARAT-EQ",
    "NSE:DIVISLAB-EQ",
    "NSE:DIXON-EQ",
    "NSE:DRREDDY-EQ",
    "NSE:EICHERMOT-EQ",
    "NSE:FORTIS-EQ",
    "NSE:GLENMARK-EQ",
    "NSE:GODREJCP-EQ",
    "NSE:GODREJPROP-EQ",
    "NSE:GRANULES-EQ",
    "NSE:GRASIM-EQ",
    "NSE:HCLTECH-EQ",
    "NSE:HDFCAMC-EQ",
    "NSE:HDFCBANK-EQ",
    "NSE:HDFCLIFE-EQ",
    "NSE:HAVELLS-EQ",
    "NSE:HEROMOTOCO-EQ",
    "NSE:HINDALCO-EQ",
    "NSE:HAL-EQ",
    "NSE:HINDUNILVR-EQ",
    "NSE:HINDZINC-EQ",
    "NSE:ICICIBANK-EQ",
    "NSE:ICICIGI-EQ",
    "NSE:ICICIPRULI-EQ",
    "NSE:IIFL-EQ",
    "NSE:ITC-EQ",
    "NSE:INDIANB-EQ",
    "NSE:IRCTC-EQ",
    "NSE:INDUSTOWER-EQ",
    "NSE:INDUSINDBK-EQ",
    "NSE:NAUKRI-EQ",
    "NSE:INFY-EQ",
    "NSE:INDIGO-EQ",
    "NSE:JSWENERGY-EQ",
    "NSE:JSWSTEEL-EQ",
    "NSE:JSL-EQ",
    "NSE:JINDALSTEL-EQ",
    "NSE:JIOFIN-EQ",
    "NSE:JUBLFOOD-EQ",
    "NSE:KEI-EQ",
    "NSE:KPITTECH-EQ",
    "NSE:KALYANKJIL-EQ",
    "NSE:KAYNES-EQ",
    "NSE:KOTAKBANK-EQ",
    "NSE:LICHSGFIN-EQ",
    "NSE:LTIM-EQ",
    "NSE:LT-EQ",
    "NSE:LAURUSLABS-EQ",
    "NSE:LICI-EQ",
    "NSE:LUPIN-EQ",
    "NSE:LODHA-EQ",
    "NSE:MGL-EQ",
    "NSE:M&M-EQ",
    "NSE:MANKIND-EQ",
    "NSE:MARICO-EQ",
    "NSE:MARUTI-EQ",
    "NSE:MFSL-EQ",
    "NSE:MAXHEALTH-EQ",
    "NSE:MAZDOCK-EQ",
    "NSE:MPHASIS-EQ",
    "NSE:MCX-EQ",
    "NSE:MUTHOOTFIN-EQ",
    "NSE:NESTLEIND-EQ",
    "NSE:OBEROIRLTY-EQ",
    "NSE:ONGC-EQ",
    "NSE:OIL-EQ",
    "NSE:PAYTM-EQ",
    "NSE:OFSS-EQ",
    "NSE:POLICYBZR-EQ",
    "NSE:PIIND-EQ",
    "NSE:PNBHOUSING-EQ",
    "NSE:PAGEIND-EQ",
    "NSE:PATANJALI-EQ",
    "NSE:PERSISTENT-EQ",
    "NSE:PIDILITIND-EQ",
    "NSE:PEL-EQ",
    "NSE:POLYCAB-EQ",
    "NSE:POONAWALLA-EQ",
    "NSE:PRESTIGE-EQ",
    "NSE:PNB-EQ",
    "NSE:RELIANCE-EQ",
    "NSE:SBICARD-EQ",
    "NSE:SBILIFE-EQ",
    "NSE:SHREECEM-EQ",
    "NSE:SRF-EQ",
    "NSE:SHRIRAMFIN-EQ",
    "NSE:SIEMENS-EQ",
    "NSE:SOLARINDS-EQ",
    "NSE:SONACOMS-EQ",
    "NSE:SBIN-EQ",
    "NSE:SUNPHARMA-EQ",
    "NSE:SUPREMEIND-EQ",
    "NSE:SYNGENE-EQ",
    "NSE:TATACONSUM-EQ",
    "NSE:TITAGARH-EQ",
    "NSE:TVSMOTOR-EQ",
    "NSE:TATACHEM-EQ",
    "NSE:TATACOMM-EQ",
    "NSE:TCS-EQ",
    "NSE:TATAELXSI-EQ",
    "NSE:TATAMOTORS-EQ",
    "NSE:TATAPOWER-EQ",
    "NSE:TATATECH-EQ",
    "NSE:TECHM-EQ",
    "NSE:INDHOTEL-EQ",
    "NSE:PHOENIXLTD-EQ",
    "NSE:TITAN-EQ",
    "NSE:TORNTPHARM-EQ",
    "NSE:TORNTPOWER-EQ",
    "NSE:TRENT-EQ",
    "NSE:TIINDIA-EQ",
    "NSE:UNOMINDA-EQ",
    "NSE:UPL-EQ",
    "NSE:ULTRACEMCO-EQ",
    "NSE:UNITDSPR-EQ",
    "NSE:VBL-EQ",
    "NSE:VEDL-EQ",
    "NSE:VOLTAS-EQ",
    "NSE:ZYDUSLIFE-EQ"
];

// let currentOptionsSymbols = [];

async function updateOptionSymbols() {
    // const newSymbols = [];
    // const sleep = ms => new Promise(r => setTimeout(r, ms));

    // for (const underlying of UNDERLYINGS) {
    //     const res = await fyersService.getOptionChain(underlying, 3);

    //     if (res.s === "ok" && res.data?.optionsChain?.length) {
    //         res.data.optionsChain.forEach(opt => {
    //             if (opt.symbol) newSymbols.push(opt.symbol);
    //         });
    //     }

    //     await sleep(1000); // prevent rate limit
    // }

    // if (newSymbols.length > 0 && websocketService.isConnected()) {
    // if (currentOptionsSymbols.length) {
    //     websocketService.unsubscribe(currentOptionsSymbols);
    // }
    // const eqSymbols = newSymbols.filter(symbol => symbol.endsWith('EQ'));

    await websocketService.subscribe(UNDERLYINGS);
    // currentOptionsSymbols = newSymbols;

    console.log(`📊 Subscribed to ${UNDERLYINGS.length} option symbols`);
    // if (eqSymbols.length > 0) {
    //     console.log(`📈 Stock symbols ending with 'EQ':`, eqSymbols.length, eqSymbols);
    // }
    // }
}

module.exports = { updateOptionSymbols };
